name: Sync Upstream

on:
  schedule:
    - cron: "0 7 * * *"   # 每天 UTC 07:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync upstream
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/SzeMeng76/LunaTV"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
